FROM ubuntu:latest

RUN apt-get -y update && apt-get -y upgrade \
    && apt-get -y instal openjdk-8-jdk wget
RUN mkdir /usr/local/jenkins
RUN wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
RUN sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
RUN apt-get install jenkins
RUN systemctl enable jenkins && systemctl start jenkins
EXPOSE 7070
